### PR TITLE
Minor fixes and copyediting

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Review by strega-nil — CHANGES_REQUESTED** [review]
Squash pls

**Comment by solson** [comment]
@ubsan GitHub has a "Squash and merge" button now, if you click the arrow next to the merge button.

**Comment by strega-nil** [comment]
@solson That is beautiful.

**Comment by joshtriplett** [comment]
@ubsan Doesn't matter much since we're planning to post the style guide as a unit, but I tend to make one commit per logical change, rather than a commit whose title couldn't be anything other than "a variety of unrelated edits".  Why the squash?

**Comment by strega-nil** [comment]
@joshtriplett Because they're generally "copyedit changes". Reading 5 commits of copyedits is annoying.

**Pull request merged**
